max_epochs: null
max_steps: 100000
gpus: 1
trainer:
  lr: 2e-5
data:
  image_size: 32
  folder: "/mnt/1000gb/cifar10/train"
  batch_size: 32
  num_workers: 10
  split_frac: 0.8 # .8 train, .1 test .1 validation
ema: # Exponential moving average
  beta: 0.995
